DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT(11) NOT NULL UNIQUE AUTO_INCREMENT,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  register DATETIME NOT NULL,
  image BOOLEAN DEFAULT FALSE,
  PRIMARY KEY  (id)
);

CREATE TABLE tasks (
  id INT(11) NOT NULL UNIQUE AUTO_INCREMENT,
  uid INT(11) NOT NULL,
  date DATETIME,
  description VARCHAR(200) NOT NULL,
  complete BOOLEAN DEFAULT FALSE,
  PRIMARY KEY  (id)
);
