version: '3.3'
services:
  web:
    container_name: php73
    build:
      context: ./www
      dockerfile: dockerphp.config
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: mysql8
    build:
      context: ./www
      dockerfile: dockermysql.config
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 6033:3306
