version: '3.3'
services:
  db:
    container_name: mysql_db
    build:
      context: ./
      dockerfile: dockerdb.config
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
  web:
    container_name: web_app
    build:
      context: ./
      dockerfile: dockerapp.config
    depends_on:
      - db
    volumes:
      - ../www/:/opt/data/
    ports:
      - 8000:80